baseURL = 'https://intellectuallyswole.github.io/'
languageCode = 'en-us'
title = 'Unconscious BIOS'

author = "Madelaine Boyd"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Unconscious BIOS"
#  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "Posts"
    url = "/posts/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/intellectuallyswole"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/madelaineboyd"
    weight = 4
[[menu.primary]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5
